title: Armand Lachand
description: Personal website
author: Armand Lachand
github: https://github.com/alachand
about: "Frelance researcher in French Guyana : Number Theory, Cryptanalysis and Machine Learning"
#I am freelance developer. Currently doing more in backend, focused in Python and Django.
#disqus_shortname: stackproblems
#google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

#exclude: [build, templates, requirements.txt, README.md, Makefile, generate.py, cv.yaml, Gemfile, LICENSE*]


enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-envelope
      link: "mailto:research@lachand.net"
    - icon: fa-tel
      link: "tel:+33769143321"
    - icon: hal-icon
      link: "https://hal.archives-ouvertes.fr/search/index/q/%2A/authIdHal_s/armandlachand/"
  #  - icon: fa-linkedin
  #    link: "https://www.linkedin.com/in/summonagus"
  #  - icon: fa-stack-exchange
  #    link: "#"
    - icon: fa-github
      link: "https://github.com/alachand"

share:
  #twitter_username: agusmakmun6
  #fb_appid: 1749788565247320

urls:
    - text: CV
      url: /cv/
    # - text: Projects
    #   url: /projects/
    - text: Research
      url : /research/
    - text: Teaching
      url: /teaching/
    - text: Freedom and alternatives
      url: /alternatives/
    #- text: Research tips
     # url: /researchresources/
 #   - text: Feed
 #     url: /feed.xml

url: "https://alachand.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

#compress_html:
#  clippings: all
#  comments: ["<!-- ", " -->"]
#  endings: all
